# 向量外积（Outer Product）

## 🔷 基础定义

**向量外积（Outer Product）** 是两个向量之间的二元运算，记作 $\vec{u} \otimes \vec{v}$ 或 $\vec{u}\vec{v}^T$，结果是一个矩阵。

### 数学表达式
对于列向量 $\vec{u} \in \mathbb{R}^m$ 和 $\vec{v} \in \mathbb{R}^n$：

$$
\vec{u} \otimes \vec{v} = \vec{u}\vec{v}^T =
\begin{pmatrix}
u_1 \\ u_2 \\ \vdots \\ u_m
\end{pmatrix}
\begin{pmatrix}
v_1 & v_2 & \cdots & v_n
\end{pmatrix} =
\begin{pmatrix}
u_1v_1 & u_1v_2 & \cdots & u_1v_n \\
u_2v_1 & u_2v_2 & \cdots & u_2v_n \\
\vdots & \vdots & \ddots & \vdots \\
u_mv_1 & u_mv_2 & \cdots & u_mv_n
\end{pmatrix}
$$

---

## 🧮 PyTorch 实现

### `torch.outer` 函数
```python
import torch

# 两个一维向量的外积
u = torch.tensor([1.0, 2.0, 3.0])  # 长度为 3
v = torch.tensor([4.0, 5.0])       # 长度为 2

outer_result = torch.outer(u, v)
print(outer_result)
# tensor([[ 4.,  5.],
#         [ 8., 10.],
#         [12., 15.]])
```

---

## 📊 维度关系

| 输入向量 |输入形状	| 输出矩阵 |输出形状 |
|----------|------|----------|------|
| $\vec{u}$ | $(m,)$ | $\vec{u} \otimes \vec{v}$ | $(m, n)$ |
| $\vec{v}$ | $(n,)$ | - | - |

---

## 🧮 重要性质

| 性质 |表达式------------------------------------------------------|
|------|--------|
| **非交换性** | $\vec{u} \otimes \vec{v} \neq \vec{v} \otimes \vec{u}$ |
| **线性性** | $(a\vec{u}) \otimes \vec{v} = \vec{u} \otimes (a\vec{v}) = a(\vec{u} \otimes \vec{v})$ |
| **分配性** | $(\vec{u_1} + \vec{u_2}) \otimes \vec{v} = \vec{u_1} \otimes \vec{v} + \vec{u_2} \otimes \vec{v}$ |

---

## 📐 应用场景

### 1. **张量积空间**
- 构建更高维的张量空间
- 量子力学中的态叠加

### 2. **协方差矩阵构建**
```python
# 简化的协方差计算
data = torch.randn(100, 3)  # 100个3维样本
mean_centered = data - data.mean(dim=0, keepdim=True)
cov_matrix = torch.zeros(3, 3)
for sample in mean_centered:
    cov_matrix += torch.outer(sample, sample)
```

### 3. **核函数计算**
- 高斯过程中的协方差矩阵
- 机器学习中的核技巧

### 4. **图像处理**
- 二维滤波器的构建
- 卷积核的张量积表示

---

## 🧪 实际应用示例

```python
import torch

# 示例1：构建二次型矩阵
x = torch.tensor([1.0, 2.0])
quadratic_matrix = torch.outer(x, x)
print("Quadratic form matrix:")
print(quadratic_matrix)
# tensor([[1., 2.],
#         [2., 4.]])

# 示例2：离散卷积核构造
kernel_1d = torch.tensor([0.25, 0.5, 0.25])
kernel_2d = torch.outer(kernel_1d, kernel_1d)
print("\n2D convolution kernel:")
print(kernel_2d)
# tensor([[0.0625, 0.1250, 0.0625],
#         [0.1250, 0.2500, 0.1250],
#         [0.0625, 0.1250, 0.0625]])

# 示例3：概率分布的联合分布
p_x = torch.tensor([0.3, 0.7])
p_y = torch.tensor([0.4, 0.4, 0.2])
joint_dist = torch.outer(p_x, p_y)
print("\nJoint probability distribution:")
print(joint_dist)
# tensor([[0.1200, 0.1200, 0.0600],
#         [0.2800, 0.2800, 0.1400]])
```

---

## 🔍 与内积的区别

| 对比项 | 内积（点积） | 外积 |
|--------|--------------|------|
| 符号 | $\vec{u} \cdot \vec{v}$ 或 $\langle\vec{u},\vec{v}\rangle$ | $\vec{u} \otimes \vec{v}$ |
| 输入 | 两个相同维度向量 | 任意维度向量 |
| 输出 | 标量 | 矩阵 |
| 形状 | - | $(m,n)$ |
| PyTorch 函数 | `torch.dot`, `torch.inner` | `torch.outer` |

---

## ⚠️ 注意事项

- **输入要求**: 仅接受一维向量作为输入
- **内存消耗**: 输出矩阵大小为 $m \times n$，当向量很长时需注意内存使用
- **数值稳定性**: 避免在极大数据上使用，可能导致数值溢出

# 向量叉积的数学含义

## 🔷 基础定义

**向量叉积（Cross Product）** 是两个 3D 向量之间的二元运算，记作 $\vec{a} \times \vec{b}$，结果是一个新的向量。

### 数学表达式
对于 $\vec{a} = (a_1, a_2, a_3)$ 和 $\vec{b} = (b_1, b_2, b_3)$：

$$
\vec{a} \times \vec{b} =
\begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3
\end{vmatrix} =
(a_2b_3 - a_3b_2)\mathbf{i} - (a_1b_3 - a_3b_1)\mathbf{j} + (a_1b_2 - a_2b_1)\mathbf{k}
$$

---

## 🧮 几何性质

### 1. **方向特性**
- **垂直性**: $\vec{a} \times \vec{b}$ 同时垂直于 $\vec{a}$ 和 $\vec{b}$
- **右手定则**: 右手四指从 $\vec{a}$ 转向 $\vec{b}$，拇指指向叉积方向

### 2. **模长特性**
$$
|\vec{a} \times \vec{b}| = |\vec{a}||\vec{b}|\sin\theta
$$
其中 $\theta$ 是两向量夹角。

### 3. **特殊情况**
- **平行向量**: $\vec{a} \parallel \vec{b} \Rightarrow \vec{a} \times \vec{b} = \vec{0}$
- **垂直向量**: $|\vec{a} \times \vec{b}| = |\vec{a}||\vec{b}|$

---

## 📊 物理意义

| 应用领域 | 物理量 | -------公式---------- |
|----------|--------|------|
| **力矩** | 力矩 $\vec{\tau}$ | $\vec{\tau} = \vec{r} \times \vec{F}$ |
| **角动量** | 角动量 $\vec{L}$ | $\vec{L} = \vec{r} \times \vec{p}$ |
| **洛伦兹力** | 磁场力 $\vec{F}$ | $\vec{F} = q(\vec{v} \times \vec{B})$ |
| **面积计算** | 平行四边形面积 | $S = |\vec{a} \times \vec{b}|$ |

---

## 🧮 代数性质

| 性质 | ------------------表达式------------------------ |
|------|--------|
| **反交换律** | $\vec{a} \times \vec{b} = -(\vec{b} \times \vec{a})$ |
| **分配律** | $\vec{a} \times (\vec{b} + \vec{c}) = \vec{a} \times \vec{b} + \vec{a} \times \vec{c}$ |
| **标量乘法** | $(k\vec{a}) \times \vec{b} = k(\vec{a} \times \vec{b})$ |
| **雅可比恒等式** | $\vec{a} \times (\vec{b} \times \vec{c}) + \vec{b} \times (\vec{c} \times \vec{a}) + \vec{c} \times (\vec{a} \times \vec{b}) = \vec{0}$ |

---

## 📐 几何应用

### 1. **法向量计算**
```python
# 三角形法向量
edge1 = vertex2 - vertex1
edge2 = vertex3 - vertex1
normal = edge1 × edge2
```

### 2. **面积计算**
- 平行四边形面积: $|\vec{a} \times \vec{b}|$
- 三角形面积: $\frac{1}{2}|\vec{a} \times \vec{b}|$

### 3. **体积计算**
- 平行六面体体积: $|\vec{a} \cdot (\vec{b} \times \vec{c})|$（标量三重积）

---

## 🧪 示例验证

设 $\vec{a} = (1, 0, 0)$，$\vec{b} = (0, 1, 0)$：

- $\vec{a} \times \vec{b} = (0, 0, 1)$（z轴方向）
- $|\vec{a} \times \vec{b}| = 1 = |\vec{a}||\vec{b}|\sin(90°)$
- 方向垂直于 xy 平面

---

## ⚠️ 重要提醒

- **仅限三维**: 叉积只在 3D 空间中有明确定义
- **反对称性**: 顺序不可交换（$\vec{a} \times \vec{b} \neq \vec{b} \times \vec{a}$）
- **零向量**: 当两向量平行时，叉积为零向量